Problem 1: Array Creation

In [1]:
import numpy as np

1. Initialize an empty array with size 2X2

In [2]:
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[1.80509285e-316 0.00000000e+000]
 [1.74736711e-316 1.75037656e-316]]


2. Initialize an all-one array with size 4X2

In [3]:
ones_array = np.ones((4, 2))
print("All-One Array:\n", ones_array)

All-One Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value

In [4]:
fill_value_array = np.full((3, 3), 7)
print("Filled Array:\n", fill_value_array)

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with the same shape and type as a given array

In [5]:
example_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(example_array)
print("Zeros Like Array:\n", zeros_like_array)

Zeros Like Array:
 [[0 0 0]
 [0 0 0]]


5. Return a new array of ones with the same shape and type as a given array

In [6]:
ones_like_array = np.ones_like(example_array)
print("Ones Like Array:\n", ones_like_array)

Ones Like Array:
 [[1 1 1]
 [1 1 1]]


 6. Convert a list to a NumPy array

In [7]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array:\n", numpy_array)

Converted NumPy Array:
 [1 2 3 4]


Problem 2: Array Manipulation

In [8]:
import numpy as np

1. Create an array with values ranging from 10 to 49

In [9]:
range_array = np.arange(10, 50)
print("Range Array:\n", range_array)

Range Array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8

In [10]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:\n", matrix_3x3)

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix

In [11]:
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean

In [12]:
random_array = np.random.random(30)
print("Random Array Mean:\n", random_array.mean())

Random Array Mean:
 0.3790937821249201


5. Create a 10X10 array with random values and find the min and max values

In [13]:
random_matrix = np.random.random((10, 10))
print("Min Value:", random_matrix.min(), "Max Value:", random_matrix.max())

Min Value: 0.054561763760777704 Max Value: 0.9985392874927397


6. Create a zero array of size 10 and replace 5th element with 1

In [14]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("Modified Zero Array:\n", zero_array)

Modified Zero Array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array

In [16]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


 8. Create a 2D array with 1 on the border and 0 inside

In [15]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("Border Array:\n", border_array)

Border Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create an 8X8 matrix and fill it with a checkerboard pattern

In [17]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:\n", checkerboard)


Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3: Array Operations

In [18]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

1. Add the two arrays

In [19]:
sum_array = x + y
print("Sum of x and y:\n", sum_array)

Sum of x and y:
 [[ 6  8]
 [10 13]]


2. Subtract the two arrays

In [21]:
diff_array = x - y
print("Difference of x and y:\n", diff_array)

Difference of x and y:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integer

In [22]:
scaled_array = x * 3
print("Scaled x by 3:\n", scaled_array)

Scaled x by 3:
 [[ 3  6]
 [ 9 15]]


4. Find the square of each element

In [23]:
squared_array = np.square(x)
print("Squared x:\n", squared_array)

Squared x:
 [[ 1  4]
 [ 9 25]]


5. Find the dot product between v and w, x and v, x and y

In [24]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product v.w:", dot_vw)
print("Dot Product x.v:\n", dot_xv)
print("Dot Product x.y:\n", dot_xy)


Dot Product v.w: 219
Dot Product x.v:
 [29 77]
Dot Product x.y:
 [[19 22]
 [50 58]]


 6. Concatenate x and y along rows, and concatenate v and w along columns

In [25]:
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("Concatenated x and y along rows:\n", concat_xy)
print("Concatenated v and w along columns:\n", concat_vw)

Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 10]
 [11 12]]


7. Attempt to concatenate x and v (which will cause an error)

In [27]:
try:
    v_reshaped = v.reshape(1, -1)
    concat_xv = np.concatenate((x, v_reshaped), axis=0)
    print("Concatenated x and v:\n", concat_xv)
except ValueError as e:
    print("Error when concatenating x and v:", e)

Concatenated x and v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem- 4: Matrix Operations:

1. Prove
𝐴
⋅
𝐴
−
1
=
𝐼
A⋅A
−1
 =I

In [28]:
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

print("A * A^-1 =\n", result)


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove
𝐴
𝐵
=
𝐵
𝐴
AB=BA

In [29]:

B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


3. Prove
(
𝐴
𝐵
)
𝑇
=
𝐵
𝑇
𝐴
𝑇
(AB)
T
 =B
T
 A
T

In [30]:
AB_T = np.transpose(AB)

B_T = np.transpose(B)
A_T = np.transpose(A)

print("Transpose of AB =\n", AB_T)
print("B^T * A^T =\n", np.dot(B_T, A_T))


Transpose of AB =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]


4. Solve the System of Linear Equations using Inverse Methods
Given the system of linear equations:

2
𝑥
−
3
𝑦
+
𝑧
=
−
1
2x−3y+z=−1
𝑥
−
𝑦
+
2
𝑧
=
−
3
x−y+2z=−3
3
𝑥
+
𝑦
−
𝑧
=
9
3x+y−z=9
This can be written in matrix form as
𝐴
𝑋
=
𝐵
AX=B, where:

𝐴
=
(
2
−
3
1
1
−
1
2
3
1
−
1
)
A=
​
  
2
1
3
​
  
−3
−1
1
​
  
1
2
−1
​
  
​

𝑋
=
(
𝑥
𝑦
𝑧
)
X=
​
  
x
y
z
​
  
​

𝐵
=
(
−
1
−
3
9
)
B=
​
  
−1
−3
9
​
  
​


In [31]:
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])


A_inv_eq = np.linalg.inv(A_eq)

X = np.dot(A_inv_eq, B_eq)

print("Solution for [x, y, z]:", X)


Solution for [x, y, z]: [ 2.  1. -2.]


5. Solve the System using np.linalg.inv function

In [32]:
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

A_inv_eq = np.linalg.inv(A_eq)

X = np.dot(A_inv_eq, B_eq)

print("Solution for [x, y, z]:", X)


Solution for [x, y, z]: [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

In [40]:
import time
import numpy as np

 1. Element-wise Addition

In [36]:
# Using Python Lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()
print("Time taken for element-wise addition with Python lists: ", end_time - start_time)

# Using NumPy Arrays
np_list1 = np.array(list1)
np_list2 = np.array(list2)
start_time = time.time()
np_sum = np_list1 + np_list2
end_time = time.time()
print("Time taken for element-wise addition with NumPy arrays: ", end_time - start_time)

Time taken for element-wise addition with Python lists:  0.10387372970581055
Time taken for element-wise addition with NumPy arrays:  0.0045168399810791016


2. Element-wise Multiplication

In [37]:
# Using Python Lists
start_time = time.time()
list_mult = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()
print("Time taken for element-wise multiplication with Python lists: ", end_time - start_time)

# Using NumPy Arrays
start_time = time.time()
np_mult = np_list1 * np_list2
end_time = time.time()
print("Time taken for element-wise multiplication with NumPy arrays: ", end_time - start_time)


Time taken for element-wise multiplication with Python lists:  0.08056926727294922
Time taken for element-wise multiplication with NumPy arrays:  0.0025582313537597656


3. Dot Product

In [38]:
# Using Python Lists
start_time = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()
print("Time taken for dot product with Python lists: ", end_time - start_time)

# Using NumPy Arrays
start_time = time.time()
np_dot_product = np.dot(np_list1, np_list2)
end_time = time.time()
print("Time taken for dot product with NumPy arrays: ", end_time - start_time)

Time taken for dot product with Python lists:  0.11199712753295898
Time taken for dot product with NumPy arrays:  0.0024344921112060547


 4. Matrix Multiplication

In [41]:
# Using Python Lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]
start_time = time.time()
matrix_mult = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
print("Time taken for matrix multiplication with Python lists: ", end_time - start_time)

# Using NumPy Arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)
start_time = time.time()
np_matrix_mult = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print("Time taken for matrix multiplication with NumPy arrays: ", end_time - start_time)


Time taken for matrix multiplication with Python lists:  193.27796912193298
Time taken for matrix multiplication with NumPy arrays:  1.6487815380096436
